version: "3.8"
services:
  service1:
    image: monster-encounter-front:v1
    build: ./front_end
    container_name: front_end
    networks: 
      - d&d-net

  service2:
    image: monster-encounter-monster-species:v1
    build: ./monster_species
    container_name: monster_species
    networks:
      - d&d-net

  service3:
    image: monster-encounter-monster-type:v1
    build: ./monster_type
    container_name: monster_type
    networks:
      - d&d-net

  service4:
    image: monster-encounter-monster-classification:v3
    build: ./monster_class
    container_name: monster_class
    networks:
      - d&d-net

  nginx:
    image: nginx:latest
    container_name: nginx
    networks:
      - d&d-net
    volumes:
      - type: bind
        source: ./nginx.conf
        target: /etc/nginx/nginx.conf
    ports: 
      - target: 80
        published: 80
        protocol: tcp
    depends_on:
      - service1

networks: 
  d&d-net:
