version: "3.8"
services:
  service1:
    image: ashtroboy/monster-encounter-front:v1a
    build: ./front_end
    container_name: front_end
    networks: 
      - dandd-net
    deploy:
      replicas: 2
    
  service2:
    image: ashtroboy/monster-encounter-monster-species:v1a
    build: ./monster_species
    container_name: monster_species
    networks:
      - dandd-net
    deploy:
      replicas: 2

  service3:
    image: ashtroboy/monster-encounter-monster-type:v1a
    build: ./monster_type
    container_name: monster_type
    networks:
      - dandd-net
    deploy:
      replicas: 2

  service4:
    image: ashtroboy/monster-encounter-monster-classification:v1a
    build: ./monster_class
    container_name: monster_class
    networks:
      - dandd-net
    deploy:
      replicas: 2

  nginx:
    image: nginx:latest
    container_name: nginx
    networks:
      - dandd-net
    volumes:
      - type: bind
        source: ./nginx.conf
        target: /etc/nginx/nginx.conf
    ports: 
      - target: 80
        published: 80
        protocol: tcp
    depends_on:
      - service1

networks: 
  dandd-net:
    driver: overlay
