- hosts: 
  - manager
  # - workers
  - load-balancer
  become: yes
  roles:
    - docker-install

- hosts:
  - manager
  become: yes
  roles:
    - swarm-init

# - hosts:
#   - workers
#   become: yes
#   roles: 
#     - swarm-join

  - hosts:
    - load-balancer
    become: yes
    roles:  
      - load-balancer
